// Code generated by MockGen. DO NOT EDIT.
// Source: exec_target.go
//
// Generated by this command:
//
//	mockgen -source exec_target.go -destination mock_agent_repo/mock_exec_target.go
//

// Package mock_agent_repo is a generated GoMock package.
package mock_agent_repo

import (
	context "context"
	reflect "reflect"

	agent_entity "github.com/agentre-ai/agentre/internal/model/entity/agent_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentExecTargetRepo is a mock of AgentExecTargetRepo interface.
type MockAgentExecTargetRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAgentExecTargetRepoMockRecorder
	isgomock struct{}
}

// MockAgentExecTargetRepoMockRecorder is the mock recorder for MockAgentExecTargetRepo.
type MockAgentExecTargetRepoMockRecorder struct {
	mock *MockAgentExecTargetRepo
}

// NewMockAgentExecTargetRepo creates a new mock instance.
func NewMockAgentExecTargetRepo(ctrl *gomock.Controller) *MockAgentExecTargetRepo {
	mock := &MockAgentExecTargetRepo{ctrl: ctrl}
	mock.recorder = &MockAgentExecTargetRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentExecTargetRepo) EXPECT() *MockAgentExecTargetRepoMockRecorder {
	return m.recorder
}

// ListByAgent mocks base method.
func (m *MockAgentExecTargetRepo) ListByAgent(ctx context.Context, agentID int64) ([]*agent_entity.AgentExecTarget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAgent", ctx, agentID)
	ret0, _ := ret[0].([]*agent_entity.AgentExecTarget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAgent indicates an expected call of ListByAgent.
func (mr *MockAgentExecTargetRepoMockRecorder) ListByAgent(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAgent", reflect.TypeOf((*MockAgentExecTargetRepo)(nil).ListByAgent), ctx, agentID)
}

// ListByAgents mocks base method.
func (m *MockAgentExecTargetRepo) ListByAgents(ctx context.Context, agentIDs []int64) (map[int64][]*agent_entity.AgentExecTarget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAgents", ctx, agentIDs)
	ret0, _ := ret[0].(map[int64][]*agent_entity.AgentExecTarget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAgents indicates an expected call of ListByAgents.
func (mr *MockAgentExecTargetRepoMockRecorder) ListByAgents(ctx, agentIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAgents", reflect.TypeOf((*MockAgentExecTargetRepo)(nil).ListByAgents), ctx, agentIDs)
}

// Replace mocks base method.
func (m *MockAgentExecTargetRepo) Replace(ctx context.Context, agentID int64, backendIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replace", ctx, agentID, backendIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Replace indicates an expected call of Replace.
func (mr *MockAgentExecTargetRepoMockRecorder) Replace(ctx, agentID, backendIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replace", reflect.TypeOf((*MockAgentExecTargetRepo)(nil).Replace), ctx, agentID, backendIDs)
}
