// Code generated by MockGen. DO NOT EDIT.
// Source: notification.go
//
// Generated by this command:
//
//	mockgen -source notification.go -destination mock_notification_repo/mock_notification.go
//

// Package mock_notification_repo is a generated GoMock package.
package mock_notification_repo

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	notification_repo "github.com/agentre-ai/agentre/internal/daemon/repository/notification_repo"
)

// MockNotificationRepo is a mock of NotificationRepo interface.
type MockNotificationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepoMockRecorder
	isgomock struct{}
}

// MockNotificationRepoMockRecorder is the mock recorder for MockNotificationRepo.
type MockNotificationRepoMockRecorder struct {
	mock *MockNotificationRepo
}

// NewMockNotificationRepo creates a new mock instance.
func NewMockNotificationRepo(ctrl *gomock.Controller) *MockNotificationRepo {
	mock := &MockNotificationRepo{ctrl: ctrl}
	mock.recorder = &MockNotificationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepo) EXPECT() *MockNotificationRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNotificationRepo) Create(ctx context.Context, n *notification_repo.NotificationLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockNotificationRepoMockRecorder) Create(ctx, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNotificationRepo)(nil).Create), ctx, n)
}

// ListSince mocks base method.
func (m *MockNotificationRepo) ListSince(ctx context.Context, peerFingerprint, peerSessionID string, cursor int64, limit int) ([]*notification_repo.NotificationLog, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSince", ctx, peerFingerprint, peerSessionID, cursor, limit)
	ret0, _ := ret[0].([]*notification_repo.NotificationLog)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSince indicates an expected call of ListSince.
func (mr *MockNotificationRepoMockRecorder) ListSince(ctx, peerFingerprint, peerSessionID, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSince", reflect.TypeOf((*MockNotificationRepo)(nil).ListSince), ctx, peerFingerprint, peerSessionID, cursor, limit)
}

// NextSeq mocks base method.
func (m *MockNotificationRepo) NextSeq(ctx context.Context, peerFingerprint, peerSessionID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextSeq", ctx, peerFingerprint, peerSessionID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextSeq indicates an expected call of NextSeq.
func (mr *MockNotificationRepoMockRecorder) NextSeq(ctx, peerFingerprint, peerSessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextSeq", reflect.TypeOf((*MockNotificationRepo)(nil).NextSeq), ctx, peerFingerprint, peerSessionID)
}
