// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -source deps.go -destination mock_orch_svc/mock_deps.go
//

// Package mock_orch_svc is a generated GoMock package.
package mock_orch_svc

import (
	context "context"
	reflect "reflect"

	agent_entity "github.com/agentre-ai/agentre/internal/model/entity/agent_entity"
	blocks "github.com/agentre-ai/agentre/internal/service/chat_svc/blocks"
	orch_svc "github.com/agentre-ai/agentre/internal/service/orch_svc"
	gomock "go.uber.org/mock/gomock"
)

// MockChatGateway is a mock of ChatGateway interface.
type MockChatGateway struct {
	ctrl     *gomock.Controller
	recorder *MockChatGatewayMockRecorder
	isgomock struct{}
}

// MockChatGatewayMockRecorder is the mock recorder for MockChatGateway.
type MockChatGatewayMockRecorder struct {
	mock *MockChatGateway
}

// NewMockChatGateway creates a new mock instance.
func NewMockChatGateway(ctrl *gomock.Controller) *MockChatGateway {
	mock := &MockChatGateway{ctrl: ctrl}
	mock.recorder = &MockChatGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatGateway) EXPECT() *MockChatGatewayMockRecorder {
	return m.recorder
}

// AbortTurn mocks base method.
func (m *MockChatGateway) AbortTurn(ctx context.Context, sessionID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AbortTurn", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AbortTurn indicates an expected call of AbortTurn.
func (mr *MockChatGatewayMockRecorder) AbortTurn(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AbortTurn", reflect.TypeOf((*MockChatGateway)(nil).AbortTurn), ctx, sessionID)
}

// AgentStatus mocks base method.
func (m *MockChatGateway) AgentStatus(ctx context.Context, sessionID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentStatus", ctx, sessionID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AgentStatus indicates an expected call of AgentStatus.
func (mr *MockChatGatewayMockRecorder) AgentStatus(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentStatus", reflect.TypeOf((*MockChatGateway)(nil).AgentStatus), ctx, sessionID)
}

// Enqueue mocks base method.
func (m *MockChatGateway) Enqueue(ctx context.Context, sessionID int64, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, sessionID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockChatGatewayMockRecorder) Enqueue(ctx, sessionID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockChatGateway)(nil).Enqueue), ctx, sessionID, text)
}

// EnsureOrchSession mocks base method.
func (m *MockChatGateway) EnsureOrchSession(ctx context.Context, in orch_svc.EnsureOrchSessionInput) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureOrchSession", ctx, in)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureOrchSession indicates an expected call of EnsureOrchSession.
func (mr *MockChatGatewayMockRecorder) EnsureOrchSession(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureOrchSession", reflect.TypeOf((*MockChatGateway)(nil).EnsureOrchSession), ctx, in)
}

// FinalAssistantText mocks base method.
func (m *MockChatGateway) FinalAssistantText(ctx context.Context, sessionID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinalAssistantText", ctx, sessionID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinalAssistantText indicates an expected call of FinalAssistantText.
func (mr *MockChatGatewayMockRecorder) FinalAssistantText(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinalAssistantText", reflect.TypeOf((*MockChatGateway)(nil).FinalAssistantText), ctx, sessionID)
}

// LatestAssistantText mocks base method.
func (m *MockChatGateway) LatestAssistantText(ctx context.Context, sessionID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestAssistantText", ctx, sessionID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestAssistantText indicates an expected call of LatestAssistantText.
func (mr *MockChatGatewayMockRecorder) LatestAssistantText(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestAssistantText", reflect.TypeOf((*MockChatGateway)(nil).LatestAssistantText), ctx, sessionID)
}

// ObserveTurn mocks base method.
func (m *MockChatGateway) ObserveTurn(sessionID int64) (<-chan orch_svc.TurnDone, func()) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ObserveTurn", sessionID)
	ret0, _ := ret[0].(<-chan orch_svc.TurnDone)
	ret1, _ := ret[1].(func())
	return ret0, ret1
}

// ObserveTurn indicates an expected call of ObserveTurn.
func (mr *MockChatGatewayMockRecorder) ObserveTurn(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveTurn", reflect.TypeOf((*MockChatGateway)(nil).ObserveTurn), sessionID)
}

// SendAndForget mocks base method.
func (m *MockChatGateway) SendAndForget(ctx context.Context, sessionID int64, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAndForget", ctx, sessionID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAndForget indicates an expected call of SendAndForget.
func (mr *MockChatGatewayMockRecorder) SendAndForget(ctx, sessionID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAndForget", reflect.TypeOf((*MockChatGateway)(nil).SendAndForget), ctx, sessionID, text)
}

// MockAgentLookup is a mock of AgentLookup interface.
type MockAgentLookup struct {
	ctrl     *gomock.Controller
	recorder *MockAgentLookupMockRecorder
	isgomock struct{}
}

// MockAgentLookupMockRecorder is the mock recorder for MockAgentLookup.
type MockAgentLookupMockRecorder struct {
	mock *MockAgentLookup
}

// NewMockAgentLookup creates a new mock instance.
func NewMockAgentLookup(ctrl *gomock.Controller) *MockAgentLookup {
	mock := &MockAgentLookup{ctrl: ctrl}
	mock.recorder = &MockAgentLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentLookup) EXPECT() *MockAgentLookupMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockAgentLookup) Find(ctx context.Context, id int64) (*agent_entity.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*agent_entity.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockAgentLookupMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAgentLookup)(nil).Find), ctx, id)
}

// FindByName mocks base method.
func (m *MockAgentLookup) FindByName(ctx context.Context, name string) (*agent_entity.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name)
	ret0, _ := ret[0].(*agent_entity.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockAgentLookupMockRecorder) FindByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockAgentLookup)(nil).FindByName), ctx, name)
}

// List mocks base method.
func (m *MockAgentLookup) List(ctx context.Context) ([]*agent_entity.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*agent_entity.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAgentLookupMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAgentLookup)(nil).List), ctx)
}

// MockEmitter is a mock of Emitter interface.
type MockEmitter struct {
	ctrl     *gomock.Controller
	recorder *MockEmitterMockRecorder
	isgomock struct{}
}

// MockEmitterMockRecorder is the mock recorder for MockEmitter.
type MockEmitterMockRecorder struct {
	mock *MockEmitter
}

// NewMockEmitter creates a new mock instance.
func NewMockEmitter(ctrl *gomock.Controller) *MockEmitter {
	mock := &MockEmitter{ctrl: ctrl}
	mock.recorder = &MockEmitterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmitter) EXPECT() *MockEmitterMockRecorder {
	return m.recorder
}

// Emit mocks base method.
func (m *MockEmitter) Emit(ctx context.Context, name string, payload any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Emit", ctx, name, payload)
}

// Emit indicates an expected call of Emit.
func (mr *MockEmitterMockRecorder) Emit(ctx, name, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Emit", reflect.TypeOf((*MockEmitter)(nil).Emit), ctx, name, payload)
}

// MockApprovalGateway is a mock of ApprovalGateway interface.
type MockApprovalGateway struct {
	ctrl     *gomock.Controller
	recorder *MockApprovalGatewayMockRecorder
	isgomock struct{}
}

// MockApprovalGatewayMockRecorder is the mock recorder for MockApprovalGateway.
type MockApprovalGatewayMockRecorder struct {
	mock *MockApprovalGateway
}

// NewMockApprovalGateway creates a new mock instance.
func NewMockApprovalGateway(ctrl *gomock.Controller) *MockApprovalGateway {
	mock := &MockApprovalGateway{ctrl: ctrl}
	mock.recorder = &MockApprovalGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApprovalGateway) EXPECT() *MockApprovalGatewayMockRecorder {
	return m.recorder
}

// BeginToolApproval mocks base method.
func (m *MockApprovalGateway) BeginToolApproval(ctx context.Context, sessionID int64, blk *blocks.ToolApprovalBlock) (<-chan bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginToolApproval", ctx, sessionID, blk)
	ret0, _ := ret[0].(<-chan bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginToolApproval indicates an expected call of BeginToolApproval.
func (mr *MockApprovalGatewayMockRecorder) BeginToolApproval(ctx, sessionID, blk any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginToolApproval", reflect.TypeOf((*MockApprovalGateway)(nil).BeginToolApproval), ctx, sessionID, blk)
}

// FinishToolApproval mocks base method.
func (m *MockApprovalGateway) FinishToolApproval(ctx context.Context, sessionID int64, requestID, status, result string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishToolApproval", ctx, sessionID, requestID, status, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// FinishToolApproval indicates an expected call of FinishToolApproval.
func (mr *MockApprovalGatewayMockRecorder) FinishToolApproval(ctx, sessionID, requestID, status, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishToolApproval", reflect.TypeOf((*MockApprovalGateway)(nil).FinishToolApproval), ctx, sessionID, requestID, status, result)
}

// MockWorkflowReader is a mock of WorkflowReader interface.
type MockWorkflowReader struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowReaderMockRecorder
	isgomock struct{}
}

// MockWorkflowReaderMockRecorder is the mock recorder for MockWorkflowReader.
type MockWorkflowReaderMockRecorder struct {
	mock *MockWorkflowReader
}

// NewMockWorkflowReader creates a new mock instance.
func NewMockWorkflowReader(ctrl *gomock.Controller) *MockWorkflowReader {
	mock := &MockWorkflowReader{ctrl: ctrl}
	mock.recorder = &MockWorkflowReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowReader) EXPECT() *MockWorkflowReaderMockRecorder {
	return m.recorder
}

// FlowContentByID mocks base method.
func (m *MockWorkflowReader) FlowContentByID(ctx context.Context, id int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FlowContentByID", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FlowContentByID indicates an expected call of FlowContentByID.
func (mr *MockWorkflowReaderMockRecorder) FlowContentByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlowContentByID", reflect.TypeOf((*MockWorkflowReader)(nil).FlowContentByID), ctx, id)
}
