// Code generated by MockGen. DO NOT EDIT.
// Source: dispatch.go
//
// Generated by this command:
//
//	mockgen -source dispatch.go -destination mock_orch_repo/mock_dispatch.go
//

// Package mock_orch_repo is a generated GoMock package.
package mock_orch_repo

import (
	context "context"
	reflect "reflect"

	orch_entity "github.com/agentre-ai/agentre/internal/model/entity/orch_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockDispatchRepo is a mock of DispatchRepo interface.
type MockDispatchRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDispatchRepoMockRecorder
	isgomock struct{}
}

// MockDispatchRepoMockRecorder is the mock recorder for MockDispatchRepo.
type MockDispatchRepoMockRecorder struct {
	mock *MockDispatchRepo
}

// NewMockDispatchRepo creates a new mock instance.
func NewMockDispatchRepo(ctrl *gomock.Controller) *MockDispatchRepo {
	mock := &MockDispatchRepo{ctrl: ctrl}
	mock.recorder = &MockDispatchRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDispatchRepo) EXPECT() *MockDispatchRepoMockRecorder {
	return m.recorder
}

// CountByRunAgent mocks base method.
func (m *MockDispatchRepo) CountByRunAgent(ctx context.Context, runID, agentID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByRunAgent", ctx, runID, agentID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByRunAgent indicates an expected call of CountByRunAgent.
func (mr *MockDispatchRepoMockRecorder) CountByRunAgent(ctx, runID, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByRunAgent", reflect.TypeOf((*MockDispatchRepo)(nil).CountByRunAgent), ctx, runID, agentID)
}

// Create mocks base method.
func (m *MockDispatchRepo) Create(ctx context.Context, t *orch_entity.Dispatch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDispatchRepoMockRecorder) Create(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDispatchRepo)(nil).Create), ctx, t)
}

// Find mocks base method.
func (m *MockDispatchRepo) Find(ctx context.Context, id int64) (*orch_entity.Dispatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*orch_entity.Dispatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockDispatchRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockDispatchRepo)(nil).Find), ctx, id)
}

// FindBySession mocks base method.
func (m *MockDispatchRepo) FindBySession(ctx context.Context, sessionID int64) (*orch_entity.Dispatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySession", ctx, sessionID)
	ret0, _ := ret[0].(*orch_entity.Dispatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySession indicates an expected call of FindBySession.
func (mr *MockDispatchRepoMockRecorder) FindBySession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySession", reflect.TypeOf((*MockDispatchRepo)(nil).FindBySession), ctx, sessionID)
}

// ListByRun mocks base method.
func (m *MockDispatchRepo) ListByRun(ctx context.Context, runID int64) ([]*orch_entity.Dispatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByRun", ctx, runID)
	ret0, _ := ret[0].([]*orch_entity.Dispatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByRun indicates an expected call of ListByRun.
func (mr *MockDispatchRepoMockRecorder) ListByRun(ctx, runID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByRun", reflect.TypeOf((*MockDispatchRepo)(nil).ListByRun), ctx, runID)
}

// Update mocks base method.
func (m *MockDispatchRepo) Update(ctx context.Context, t *orch_entity.Dispatch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDispatchRepoMockRecorder) Update(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDispatchRepo)(nil).Update), ctx, t)
}
