// Code generated by MockGen. DO NOT EDIT.
// Source: run.go
//
// Generated by this command:
//
//	mockgen -source run.go -destination mock_orch_repo/mock_run.go
//

// Package mock_orch_repo is a generated GoMock package.
package mock_orch_repo

import (
	context "context"
	reflect "reflect"

	orch_entity "github.com/agentre-ai/agentre/internal/model/entity/orch_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockRunRepo is a mock of RunRepo interface.
type MockRunRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRunRepoMockRecorder
	isgomock struct{}
}

// MockRunRepoMockRecorder is the mock recorder for MockRunRepo.
type MockRunRepoMockRecorder struct {
	mock *MockRunRepo
}

// NewMockRunRepo creates a new mock instance.
func NewMockRunRepo(ctrl *gomock.Controller) *MockRunRepo {
	mock := &MockRunRepo{ctrl: ctrl}
	mock.recorder = &MockRunRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunRepo) EXPECT() *MockRunRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRunRepo) Create(ctx context.Context, r *orch_entity.OrchestrationRun) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRunRepoMockRecorder) Create(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRunRepo)(nil).Create), ctx, r)
}

// Find mocks base method.
func (m *MockRunRepo) Find(ctx context.Context, id int64) (*orch_entity.OrchestrationRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*orch_entity.OrchestrationRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockRunRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRunRepo)(nil).Find), ctx, id)
}

// List mocks base method.
func (m *MockRunRepo) List(ctx context.Context) ([]*orch_entity.OrchestrationRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*orch_entity.OrchestrationRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRunRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRunRepo)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockRunRepo) Update(ctx context.Context, r *orch_entity.OrchestrationRun) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRunRepoMockRecorder) Update(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRunRepo)(nil).Update), ctx, r)
}
