// Code generated by MockGen. DO NOT EDIT.
// Source: task.go
//
// Generated by this command:
//
//	mockgen -source task.go -destination mock_orch_repo/mock_task.go
//

// Package mock_orch_repo is a generated GoMock package.
package mock_orch_repo

import (
	context "context"
	reflect "reflect"

	orch_entity "github.com/agentre-ai/agentre/internal/model/entity/orch_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskRepo is a mock of TaskRepo interface.
type MockTaskRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepoMockRecorder
	isgomock struct{}
}

// MockTaskRepoMockRecorder is the mock recorder for MockTaskRepo.
type MockTaskRepoMockRecorder struct {
	mock *MockTaskRepo
}

// NewMockTaskRepo creates a new mock instance.
func NewMockTaskRepo(ctrl *gomock.Controller) *MockTaskRepo {
	mock := &MockTaskRepo{ctrl: ctrl}
	mock.recorder = &MockTaskRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepo) EXPECT() *MockTaskRepoMockRecorder {
	return m.recorder
}

// CountByRunAgent mocks base method.
func (m *MockTaskRepo) CountByRunAgent(ctx context.Context, runID, agentID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByRunAgent", ctx, runID, agentID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByRunAgent indicates an expected call of CountByRunAgent.
func (mr *MockTaskRepoMockRecorder) CountByRunAgent(ctx, runID, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByRunAgent", reflect.TypeOf((*MockTaskRepo)(nil).CountByRunAgent), ctx, runID, agentID)
}

// Create mocks base method.
func (m *MockTaskRepo) Create(ctx context.Context, t *orch_entity.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTaskRepoMockRecorder) Create(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTaskRepo)(nil).Create), ctx, t)
}

// Find mocks base method.
func (m *MockTaskRepo) Find(ctx context.Context, id int64) (*orch_entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*orch_entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockTaskRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockTaskRepo)(nil).Find), ctx, id)
}

// FindBySession mocks base method.
func (m *MockTaskRepo) FindBySession(ctx context.Context, sessionID int64) (*orch_entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySession", ctx, sessionID)
	ret0, _ := ret[0].(*orch_entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySession indicates an expected call of FindBySession.
func (mr *MockTaskRepoMockRecorder) FindBySession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySession", reflect.TypeOf((*MockTaskRepo)(nil).FindBySession), ctx, sessionID)
}

// ListByRun mocks base method.
func (m *MockTaskRepo) ListByRun(ctx context.Context, runID int64) ([]*orch_entity.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByRun", ctx, runID)
	ret0, _ := ret[0].([]*orch_entity.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByRun indicates an expected call of ListByRun.
func (mr *MockTaskRepoMockRecorder) ListByRun(ctx, runID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByRun", reflect.TypeOf((*MockTaskRepo)(nil).ListByRun), ctx, runID)
}

// Update mocks base method.
func (m *MockTaskRepo) Update(ctx context.Context, t *orch_entity.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTaskRepoMockRecorder) Update(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTaskRepo)(nil).Update), ctx, t)
}
