// Code generated by MockGen. DO NOT EDIT.
// Source: svc.go
//
// Generated by this command:
//
//	mockgen -source svc.go -destination mock_workspace_fs_svc/mock_svc.go
//

// Package mock_workspace_fs_svc is a generated GoMock package.
package mock_workspace_fs_svc

import (
	context "context"
	reflect "reflect"

	workspace_fs_svc "github.com/agentre-ai/agentre/internal/service/workspace_fs_svc"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkspaceFsSvc is a mock of WorkspaceFsSvc interface.
type MockWorkspaceFsSvc struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceFsSvcMockRecorder
	isgomock struct{}
}

// MockWorkspaceFsSvcMockRecorder is the mock recorder for MockWorkspaceFsSvc.
type MockWorkspaceFsSvcMockRecorder struct {
	mock *MockWorkspaceFsSvc
}

// NewMockWorkspaceFsSvc creates a new mock instance.
func NewMockWorkspaceFsSvc(ctrl *gomock.Controller) *MockWorkspaceFsSvc {
	mock := &MockWorkspaceFsSvc{ctrl: ctrl}
	mock.recorder = &MockWorkspaceFsSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspaceFsSvc) EXPECT() *MockWorkspaceFsSvcMockRecorder {
	return m.recorder
}

// GitBranches mocks base method.
func (m *MockWorkspaceFsSvc) GitBranches(ctx context.Context, sessionID int64) (*workspace_fs_svc.GitBranchesView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GitBranches", ctx, sessionID)
	ret0, _ := ret[0].(*workspace_fs_svc.GitBranchesView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GitBranches indicates an expected call of GitBranches.
func (mr *MockWorkspaceFsSvcMockRecorder) GitBranches(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GitBranches", reflect.TypeOf((*MockWorkspaceFsSvc)(nil).GitBranches), ctx, sessionID)
}

// GitChanges mocks base method.
func (m *MockWorkspaceFsSvc) GitChanges(ctx context.Context, sessionID int64, scope, baseRef string) (*workspace_fs_svc.GitChangesView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GitChanges", ctx, sessionID, scope, baseRef)
	ret0, _ := ret[0].(*workspace_fs_svc.GitChangesView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GitChanges indicates an expected call of GitChanges.
func (mr *MockWorkspaceFsSvcMockRecorder) GitChanges(ctx, sessionID, scope, baseRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GitChanges", reflect.TypeOf((*MockWorkspaceFsSvc)(nil).GitChanges), ctx, sessionID, scope, baseRef)
}

// ListDir mocks base method.
func (m *MockWorkspaceFsSvc) ListDir(ctx context.Context, sessionID int64, relPath string, includeIgnored bool) (*workspace_fs_svc.ListDirView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDir", ctx, sessionID, relPath, includeIgnored)
	ret0, _ := ret[0].(*workspace_fs_svc.ListDirView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDir indicates an expected call of ListDir.
func (mr *MockWorkspaceFsSvcMockRecorder) ListDir(ctx, sessionID, relPath, includeIgnored any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDir", reflect.TypeOf((*MockWorkspaceFsSvc)(nil).ListDir), ctx, sessionID, relPath, includeIgnored)
}
